name: Build Expo App

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: 🏗 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: 🏗 Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          token: ${{ secrets.EXPO_TOKEN }}
          expo-version: latest
          eas-version: latest
          packager: npm

      - name: 📦 Install dependencies
        run: npm ci

      - name: 👷 Build expo app
        env:
          SENTRY_URL: ${{ secrets.SENTRY_URL }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: |
          eas build --local --non-interactive --output ./jellyseerr.apk --platform android --profile preview

      - name: 📦 Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jellyseerr.apk
          path: ./jellyseerr.apk
