name: Build Expo App

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 🏗 Setup repo
      uses: actions/checkout@v4

    - name: 🏗 Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 22.x

    - name: 🏗 Setup Expo and EAS
      uses: expo/expo-github-action@v8
      with:
        token: ${{ secrets.EXPO_TOKEN }}
        expo-version: latest
        eas-version: latest
        packager: npm

    - name: 📦 Install dependencies
      run: npm install

    - name: 👷 Build expo app
      run: |
        eas build --local \
          --non-interactive \
          --output=./app-build \
          --platform=android \
          --profile=preview

    # - name: 🚢 Submit
    #   run: eas submit -p android --profile preview --path app-build

    - name: 📦 Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: app-build

    - name: 📦 Create release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref_name }}
      run: |
        gh release create "$tag" \
            --repo="$GITHUB_REPOSITORY" \
            --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
            --generate-notes